name: Deploy and Trigger Parent Repository

on:
  push:
    branches:
      - testing-gra  # Replace with the branch you want to monitor (e.g., gra-modules)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: composer install

      - name: Run deployment script
        run: |
          # Add your deployment script here
          echo "Deploying gra-modules..."

  Trigger-parent:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Trigger parent repository workflow
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo, workflow_id, ref, inputs } = {
              owner: 'sangeethdharsan',  // Replace with the parent repository's owner
              repo: 'gra_2',   // Replace with the parent repository's name
              workflow_id: 'update-from-child.yml',  // Name of the workflow in the parent repository
              ref: 'test',  // Branch where the workflow is defined in the parent repository
              inputs: {
                'child-commit-id': '${{ github.sha }}'  // Pass the commit ID of the child repository
              }
            };

            await github.rest.actions.createWorkflowDispatch({
              owner,
              repo,
              workflow_id,
              ref,
              inputs
            });
