name: Update Composer Lock in Target Repository

on:
  push:
    branches:
      - main  
      - testing-gra

jobs:
  update-composer-lock:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Child Repository
        uses: actions/checkout@v3
        with:
          repository: sangeethdharsan/gra_modules  # Replace with your child repo
          ref: ${{ github.sha }}  # Use the commit SHA that triggered the workflow

      - name: Get Commit SHA
        id: get-commit-sha
        run: echo "COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Checkout Target Repository
        uses: actions/checkout@v3
        with:
          repository: sangeethdharsan/gra_2 # Replace with your target repo
          path: gra_2
          token: ${{ secrets.PAT }}
          ref: test
          
      - name: Install Composer Dependencies in Target Repository
        run: |
          cd gra_2
          composer install --no-interaction --no-progress --no-suggest    

      - name: Update Composer Lock
        run: |
          cd gra_2
          git branch -a 
          ls -ltrh
   #      git checkout test
   #       composer config repositories.gra_modules '{"type": "vcs", "url": "https://github.com/sangeethdharsan/gra_modules.git", "branch": "testing-gra"}'
   #       composer update --lock
   #       git config --global user.name "GitHub Actions"
   #       git config --global user.email "actions@github.com"
   #       git add composer.lock
   #       git commit -m "Update composer.lock with child-repo commit ${{ env.COMMIT_SHA }}"
   #       git push origin test  # Replace with the target branch if not main
