name: Reusable Composer Update

on:
  workflow_call:
    inputs:
      target_repo:
        required: true
        type: string
      target_branch:
        required: false
        type: string
        default: 'reusable-gra'
      package_name:
        required: false
        type: string
        default: 'gratest/codingstandard-php'
      source_sha:
        required: true
        type: string
    secrets:
      target_token:
        required: true

jobs:
  update-composer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.target_repo }}
          path: target-repo
          token: ${{ secrets.target_token }}
          ref: ${{ inputs.target_branch }}

      - name: Update composer reference
        run: |
          cd target-repo
          ls -ltrh
          composer config repositories.source-repo '{
            "type": "git",
            "url": "https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}.git",
            "reference": "${{ inputs.source_sha }}"
          }'
          composer update ${{ inputs.package_name }} --with-all-dependencies

      - name: Commit and push changes
        run: |
          cd target-repo
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add composer.lock
          git commit -m "Update ${{ inputs.package_name }} to ${{ github.repository_owner }}/${{ github.event.repository.name }}@${{ inputs.source_sha }}"
          git push
