name: Trigger Workflow in Another Repo
on:
  workflow_dispatch:
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow_dispatch event
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PAT }}" \
          https://api.github.com/repos/sangeethdharsan/gra_2/actions/workflows/WORKFLOW_ID/dispatches \
          -d '{"ref":"main"}'
