name: Update Composer Lock in Target Repository

on:
  push:
    branches:
      - main  
      - testing-gra

jobs:
  updating-composer-lock:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Child Repository
        uses: actions/checkout@v3
        with:
          repository: sangeethdharsan/gra_modules  
          ref: ${{ github.sha }}

      - name: Get Commit SHA
        id: get-commit-sha
        run: echo "COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Checkout Target Repository
        uses: actions/checkout@v3
        with:
          repository: sangeethdharsan/gra_2  
          path: gra_2
          token: ${{ secrets.PAT }}  
          ref: test
          
      - name: Install Composer Dependencies
        run: |
          cd gra_2
          composer clear-cache
          composer config repositories.gra_modules '{"type": "vcs", "url": "https://github.com/sangeethdharsan/gra_modules.git", "branch": "testing-gra"}'
          composer install --no-interaction --no-progress --no-suggest    

      - name: Force Composer to Update Dependencies
        run: |
          cd gra_2
          composer require sangeethdharsan/gra_modules:dev-testing-gra --no-update
          composer update sangeethdharsan/gra_modules --with-dependencies

      - name: Debug Composer Lock Changes
        run: |
          cd gra_2
          git status
          git diff composer.lock || echo "No changes detected in composer.lock"

      - name: Commit and Push Changes
        run: |
          cd gra_2
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add composer.lock composer.json
          git commit -m "Update composer.lock with child-repo commit ${{ env.COMMIT_SHA }}" || echo "No changes to commit"
          git push origin test

